sudo: required
dist: trusty
language: node_js
node_js:
- '6.9'
cache:
  directories:
  - node_modules
addons: 
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build
script: karma start karma.conf.js --single-run
deploy:
    provider: azure_web_apps
    username: nlnTravisCi
    password: Ut0p1aBl1ss
    site: nlnationweb
    verbose: true
    skip_cleanup: true
    on: master
